//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDonHang = new HashSet<CTDonHang>();
        }
    
        public int ID_SP { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIA { get; set; }
        public string HINHANH { get; set; }
        public Nullable<System.DateTime> HANSUDUNG { get; set; }
        public bool COSAN { get; set; }
        public Nullable<int> ID_LOAI { get; set; }
        public string MOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHang { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
